-- Cache Database Schema
-- Single source of truth for cache.db
-- This schema represents the final state after all migrations

-- Recommendations table: trading plan recommendations
-- Generated by PlannerBatchJob, consumed by EventBasedTradingJob
-- Short-lived operational data (cleared after execution or expiration)
CREATE TABLE IF NOT EXISTS recommendations (
    uuid TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity REAL NOT NULL CHECK (quantity > 0),
    estimated_price REAL NOT NULL CHECK (estimated_price > 0),
    estimated_value REAL NOT NULL,
    reason TEXT NOT NULL,
    currency TEXT NOT NULL,
    priority REAL NOT NULL,
    current_portfolio_score REAL NOT NULL,
    new_portfolio_score REAL NOT NULL,
    score_change REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'rejected', 'expired')),
    portfolio_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    executed_at TEXT
) STRICT;

CREATE INDEX IF NOT EXISTS idx_recommendations_status_priority
ON recommendations(status, priority ASC, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_recommendations_portfolio_hash
ON recommendations(portfolio_hash, status);

CREATE INDEX IF NOT EXISTS idx_recommendations_executed_at
ON recommendations(executed_at) WHERE executed_at IS NOT NULL;

-- Cache data table: generic key-value cache
-- For temporary computed results that can be rebuilt
CREATE TABLE IF NOT EXISTS cache_data (
    cache_key TEXT PRIMARY KEY,
    cache_value TEXT NOT NULL,       -- JSON or serialized data
    expires_at INTEGER,              -- Unix timestamp (NULL = never expires)
    created_at INTEGER NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_cache_expires ON cache_data(expires_at);

-- Job execution history (tracks last run time per job type)
-- Used by time-based scheduler to determine if jobs should run
CREATE TABLE IF NOT EXISTS job_history (
    job_type TEXT PRIMARY KEY,
    last_run_at TEXT NOT NULL,
    last_status TEXT NOT NULL DEFAULT 'success'
) STRICT;

CREATE INDEX IF NOT EXISTS idx_job_history_last_run ON job_history(last_run_at);
