# Sentinel LED - Arduino App configuration
# Orbital portfolio visualization for Arduino UNO Q LED matrix

name: sentinel-led
description: "Orbital portfolio visualization - displays holdings as orbiting bodies"
icon: "\U0001F4CA"

# Expose no ports - this app only communicates with MCU and fetches from sentinel API
ports: []

# No bricks needed - we use Bridge directly
bricks: []
