# golangci-lint configuration for Arduino Trader
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused constants, variables, functions, types

    # Additional recommended linters
    - gofmt         # Check code is formatted
    - goimports     # Check imports are formatted
    - misspell      # Find commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gosec         # Security checker (like bandit for Python)
    - bodyclose     # Check HTTP response body is closed
    - errname       # Check error naming conventions
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping
    - gocritic      # Opinionated Go linter
    - goprintffuncname  # Check printf-like function names
    - nilerr        # Find code returning nil even when error is not nil
    - nolintlint    # Ensure //nolint directives are properly used
    - prealloc      # Find slice declarations that could potentially be preallocated
    - predeclared   # Find code that shadows Go predeclared identifiers
    - thelper       # Detect test helpers without t.Helper()
    - wastedassign  # Find wasted assignment statements

linters-settings:
  errcheck:
    # Don't check error return value for these functions
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close

  govet:
    enable-all: true
    disable:
      - shadow  # Can be overly strict

  gosec:
    # Security severity levels: LOW, MEDIUM, HIGH
    severity: medium
    confidence: medium
    excludes:
      - G104  # Unhandled errors (covered by errcheck)

  revive:
    rules:
      # Enable specific rules
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  goimports:
    local-prefixes: github.com/yourusername/arduino-trader

issues:
  # Maximum issues count per one linter (0 = unlimited)
  max-issues-per-linter: 0
  # Maximum count of issues with the same text (0 = unlimited)
  max-same-issues: 0

  # Exclude some linters from running on tests
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude known linters from partially hard-vendored code sources
    - path: "internal/vendor/"
      linters:
        - gocritic
        - staticcheck
        - revive

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
