-- Agents Database Schema
-- Migration 005: Create agents.db schema for strategy management
--
-- This migration creates tables for the agents database (renamed from planner.db):
-- - Agent configs: TOML strategy configurations (editable from UI)
-- - Config history: Version tracking and performance-based rollback
-- - Sequences: Generated trade action sequences
-- - Evaluations: Sequence evaluation results
-- - Best result: Best sequence per portfolio state
--
-- Naming change: "planner" → "agent" to clarify that these are strategy configs,
-- not AI agents. Each TOML file defines a trading strategy (agent/planner).
--
-- Data Migration Note:
-- If planner.db exists, tables will be renamed during Phase 6:
-- - planner_configs → agent_configs
-- - planner_config_history → config_history

-- Agent configurations: TOML strategy files for satellites
-- Each satellite bucket references an agent_id (TOML strategy config)
CREATE TABLE IF NOT EXISTS agent_configs (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,              -- Display name (e.g., "Aggressive Growth")
    toml_config TEXT NOT NULL,       -- TOML configuration string
    bucket_id TEXT,                  -- Associated bucket (nullable for templates)
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS idx_agent_configs_bucket ON agent_configs(bucket_id);
CREATE INDEX IF NOT EXISTS idx_agent_configs_name ON agent_configs(name);

-- Agent config history: version tracking with performance-based rollback
-- Every config change is saved here with timestamp
CREATE TABLE IF NOT EXISTS config_history (
    id TEXT PRIMARY KEY,
    agent_config_id TEXT NOT NULL,
    name TEXT NOT NULL,
    toml_config TEXT NOT NULL,
    saved_at TEXT NOT NULL,
    performance_score REAL,          -- Optional: track which version performed better
    FOREIGN KEY (agent_config_id) REFERENCES agent_configs(id) ON DELETE CASCADE
) STRICT;

CREATE INDEX IF NOT EXISTS idx_config_history_agent ON config_history(agent_config_id);
CREATE INDEX IF NOT EXISTS idx_config_history_saved ON config_history(saved_at DESC);
CREATE INDEX IF NOT EXISTS idx_config_history_performance ON config_history(agent_config_id, performance_score DESC);

-- Sequences table: candidate trade action sequences
-- Generated by planner for evaluation
CREATE TABLE IF NOT EXISTS sequences (
    sequence_hash TEXT NOT NULL,
    portfolio_hash TEXT NOT NULL,
    priority REAL NOT NULL,
    sequence_json TEXT NOT NULL,     -- JSON serialized List[ActionCandidate]
    depth INTEGER NOT NULL,          -- Sequence depth (1-5)
    pattern_type TEXT,               -- Pattern: 'direct_buy', 'combinatorial', etc.
    completed INTEGER DEFAULT 0,     -- 0 = not evaluated, 1 = evaluated
    evaluated_at TEXT,               -- ISO timestamp when evaluated
    created_at TEXT NOT NULL,
    PRIMARY KEY (sequence_hash, portfolio_hash)
) STRICT;

CREATE INDEX IF NOT EXISTS idx_sequences_portfolio ON sequences(portfolio_hash);
CREATE INDEX IF NOT EXISTS idx_sequences_priority ON sequences(portfolio_hash, priority DESC, completed);
CREATE INDEX IF NOT EXISTS idx_sequences_completed ON sequences(portfolio_hash, completed);

-- Evaluations table: evaluation results for sequences
CREATE TABLE IF NOT EXISTS evaluations (
    sequence_hash TEXT NOT NULL,
    portfolio_hash TEXT NOT NULL,
    end_score REAL NOT NULL,
    breakdown_json TEXT NOT NULL,    -- JSON serialized score breakdown
    end_cash REAL NOT NULL,
    end_context_positions_json TEXT NOT NULL,  -- JSON Dict[str, float]
    div_score REAL NOT NULL,         -- Diversification score
    total_value REAL NOT NULL,       -- Total portfolio value after sequence
    evaluated_at TEXT NOT NULL,
    PRIMARY KEY (sequence_hash, portfolio_hash)
) STRICT;

CREATE INDEX IF NOT EXISTS idx_evaluations_portfolio ON evaluations(portfolio_hash);
CREATE INDEX IF NOT EXISTS idx_evaluations_score ON evaluations(portfolio_hash, end_score DESC);

-- Best result table: best sequence found per portfolio state
CREATE TABLE IF NOT EXISTS best_result (
    portfolio_hash TEXT PRIMARY KEY,
    best_sequence_hash TEXT NOT NULL,
    best_score REAL NOT NULL,
    updated_at TEXT NOT NULL
) STRICT;
