-- Migration 025: Remove partial_execution_generator column from planner_settings
--
-- This migration removes the partial_execution_generator column from planner_settings table.
-- Partial Execution Generator was redundant - sequences of different lengths are already
-- generated by patterns and combinatorial generators.

-- Drop the partial_execution_generator column from planner_settings table
-- Note: SQLite doesn't support DROP COLUMN IF EXISTS.
-- Migration handler will skip if column doesn't exist (no such column error)
ALTER TABLE planner_settings DROP COLUMN enable_partial_execution_generator;
